// Mock Data Service - Central repository for all demo data

// User Profiles
export const mockUsers = {
    candidate: {
        id: 'user_candidate_1',
        email: 'candidate@example.com',
        role: 'candidate',
        name: 'Alex Johnson',
        avatar: null,
        profile: {
            phone: '+1 (555) 123-4567',
            location: 'San Francisco, CA',
            bio: 'Passionate software developer with 5 years of experience in full-stack development.',
            linkedin: 'https://linkedin.com/in/alexjohnson',
            github: 'https://github.com/alexjohnson',
            portfolio: 'https://alexjohnson.dev',
            education: [
                {
                    id: 'edu_1',
                    institution: 'Stanford University',
                    degree: 'Bachelor of Science',
                    field: 'Computer Science',
                    startDate: '2015-09',
                    endDate: '2019-05',
                    cgpa: 3.8,
                    maxCgpa: 4.0,
                },
            ],
            experience: [
                {
                    id: 'exp_1',
                    company: 'Tech Corp',
                    position: 'Senior Software Engineer',
                    startDate: '2021-01',
                    endDate: null,
                    current: true,
                    description: 'Leading development of microservices architecture',
                },
                {
                    id: 'exp_2',
                    company: 'StartupXYZ',
                    position: 'Full Stack Developer',
                    startDate: '2019-06',
                    endDate: '2020-12',
                    current: false,
                    description: 'Built and maintained web applications using React and Node.js',
                },
            ],
            skills: [
                { name: 'React', proficiency: 90 },
                { name: 'Node.js', proficiency: 85 },
                { name: 'TypeScript', proficiency: 80 },
                { name: 'Python', proficiency: 75 },
                { name: 'AWS', proficiency: 70 },
                { name: 'Docker', proficiency: 75 },
            ],
            projects: [
                {
                    id: 'proj_1',
                    name: 'E-commerce Platform',
                    description: 'Built a scalable e-commerce platform serving 100k+ users',
                    technologies: ['React', 'Node.js', 'MongoDB', 'AWS'],
                    url: 'https://github.com/alexjohnson/ecommerce',
                },
            ],
        },
        profileCompletion: 85,
    },
    employer: {
        id: 'user_employer_1',
        email: 'recruiter@techcorp.com',
        role: 'employer',
        name: 'Sarah Mitchell',
        avatar: null,
        company: {
            id: 'company_1',
            name: 'TechCorp Solutions',
            logo: null,
            industry: 'Technology',
            size: '500-1000',
            website: 'https://techcorp.com',
            description: 'Leading technology solutions provider',
            verified: true,
            location: 'San Francisco, CA',
        },
    },
    admin: {
        id: 'user_admin_1',
        email: 'admin@platform.com',
        role: 'admin',
        name: 'Admin User',
        avatar: null,
    },
    superadmin: {
        id: 'user_superadmin_1',
        email: 'superadmin@platform.com',
        role: 'superadmin',
        name: 'Super Admin',
        avatar: null,
    },
};

// Job Listings
export const mockJobs = [
    {
        id: 'job_1',
        title: 'Senior Full Stack Developer',
        company: 'TechCorp Solutions',
        companyId: 'company_1',
        location: 'San Francisco, CA',
        type: 'Full-time',
        salary: '₹10L - ₹15L',
        description: 'We are looking for an experienced Full Stack Developer to join our team...',
        requirements: [
            '5+ years of experience with React and Node.js',
            'Strong understanding of microservices architecture',
            'Experience with AWS or similar cloud platforms',
        ],
        responsibilities: [
            'Design and develop scalable web applications',
            'Collaborate with cross-functional teams',
            'Mentor junior developers',
        ],
        skills: ['React', 'Node.js', 'TypeScript', 'AWS', 'Docker'],
        posted: '2 days ago',
        applicants: 45,
        status: 'active',
        minCgpa: 3.0,
        experience: '5+ years',
        department: 'Engineering',
    },
    {
        id: 'job_2',
        title: 'Frontend Developer',
        company: 'Innovation Labs',
        companyId: 'company_2',
        location: 'Remote',
        type: 'Full-time',
        salary: '₹8L - ₹12L',
        description: 'Join our team to build amazing user interfaces...',
        requirements: [
            '3+ years of React experience',
            'Strong CSS and responsive design skills',
            'Experience with modern frontend tools',
        ],
        responsibilities: [
            'Build responsive web applications',
            'Collaborate with designers',
            'Optimize application performance',
        ],
        skills: ['React', 'CSS', 'JavaScript', 'Tailwind'],
        posted: '1 week ago',
        applicants: 32,
        status: 'active',
        minCgpa: 2.8,
        experience: '3+ years',
        department: 'Product',
    },
    {
        id: 'job_3',
        title: 'Backend Engineer',
        company: 'DataFlow Inc',
        companyId: 'company_3',
        location: 'New York, NY',
        type: 'Full-time',
        salary: '₹9L - ₹14L',
        description: 'Build scalable backend systems for our data platform...',
        requirements: [
            '4+ years of backend development',
            'Experience with Python or Node.js',
            'Strong database design skills',
        ],
        responsibilities: [
            'Design and implement APIs',
            'Optimize database queries',
            'Ensure system reliability',
        ],
        skills: ['Python', 'Node.js', 'PostgreSQL', 'Redis'],
        posted: '3 days ago',
        applicants: 28,
        status: 'active',
        minCgpa: 3.2,
        experience: '4+ years',
        department: 'Engineering',
    },
    {
        id: 'job_4',
        title: 'DevOps Engineer',
        company: 'CloudTech Systems',
        companyId: 'company_4',
        location: 'Austin, TX',
        type: 'Full-time',
        salary: '₹12L - ₹18L',
        description: 'Manage and optimize our cloud infrastructure...',
        requirements: [
            '5+ years of DevOps experience',
            'Expert knowledge of AWS/Azure',
            'Strong scripting skills',
        ],
        responsibilities: [
            'Manage CI/CD pipelines',
            'Monitor system performance',
            'Implement security best practices',
        ],
        skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
        posted: '5 days ago',
        applicants: 19,
        status: 'active',
        minCgpa: 3.0,
        experience: '5+ years',
        department: 'Infrastructure',
    },
    {
        id: 'job_5',
        title: 'UI/UX Designer',
        company: 'DesignHub',
        companyId: 'company_5',
        location: 'Los Angeles, CA',
        type: 'Contract',
        salary: '₹7L - ₹10L',
        description: 'Create beautiful and intuitive user experiences...',
        requirements: [
            '3+ years of UI/UX design',
            'Proficiency in Figma and Adobe XD',
            'Strong portfolio',
        ],
        responsibilities: [
            'Design user interfaces',
            'Conduct user research',
            'Create design systems',
        ],
        skills: ['Figma', 'Adobe XD', 'Sketch', 'Prototyping'],
        posted: '1 day ago',
        applicants: 52,
        status: 'active',
        minCgpa: 2.5,
        experience: '3+ years',
        department: 'Design',
    },
];

// Applications
export const mockApplications = [
    {
        id: 'app_1',
        jobId: 'job_1',
        candidateId: 'user_candidate_1',
        title: 'Senior Full Stack Developer',
        company: 'TechCorp Solutions',
        logo: 'TC',
        status: 'Interview Scheduled',
        appliedDate: '2024-01-15',
        stage: 2,
        totalStages: 4,
        interviewDate: 'Feb 10, 2024 at 2:00 PM',
        timeline: [
            { stage: 'Applied', date: '2024-01-15', completed: true },
            { stage: 'Resume Reviewed', date: '2024-01-17', completed: true },
            { stage: 'Interview Scheduled', date: '2024-01-20', completed: true },
            { stage: 'Final Decision', date: null, completed: false },
        ],
    },
    {
        id: 'app_2',
        jobId: 'job_2',
        candidateId: 'user_candidate_1',
        title: 'Frontend Developer',
        company: 'Innovation Labs',
        logo: 'IL',
        status: 'Under Review',
        appliedDate: '2024-01-18',
        stage: 1,
        totalStages: 4,
        timeline: [
            { stage: 'Applied', date: '2024-01-18', completed: true },
            { stage: 'Resume Review', date: null, completed: false },
            { stage: 'Technical Interview', date: null, completed: false },
            { stage: 'Final Decision', date: null, completed: false },
        ],
    },
    {
        id: 'app_3',
        jobId: 'job_3',
        candidateId: 'user_candidate_1',
        title: 'Backend Engineer',
        company: 'DataFlow Inc',
        logo: 'DF',
        status: 'Rejected',
        appliedDate: '2024-01-10',
        stage: 2,
        totalStages: 4,
        timeline: [
            { stage: 'Applied', date: '2024-01-10', completed: true },
            { stage: 'Resume Reviewed', date: '2024-01-12', completed: true },
            { stage: 'Rejected', date: '2024-01-14', completed: true },
        ],
    },
];

// BGV Documents
export const mockBGVDocuments = [
    {
        id: 'doc_1',
        name: 'Identity Proof (Aadhar/Passport)',
        status: 'verified',
        uploadedDate: '2024-01-05',
        verifiedDate: '2024-01-06',
        required: true,
    },
    {
        id: 'doc_2',
        name: 'Educational Certificates',
        status: 'pending',
        uploadedDate: '2024-01-10',
        verifiedDate: null,
        required: true,
    },
    {
        id: 'doc_3',
        name: 'Experience Letters',
        status: 'verified',
        uploadedDate: '2024-01-08',
        verifiedDate: '2024-01-09',
        required: true,
    },
    {
        id: 'doc_4',
        name: 'Address Proof',
        status: 'not_uploaded',
        uploadedDate: null,
        verifiedDate: null,
        required: true,
    },
    {
        id: 'doc_5',
        name: 'Police Verification',
        status: 'not_uploaded',
        uploadedDate: null,
        verifiedDate: null,
        required: false,
    },
];

// Dashboard Stats
export const mockCandidateStats = {
    applied: 12,
    interviews: 3,
    views: 245,
    saved: 8,
};

export const mockEmployerStats = {
    activeJobs: 5,
    totalApplicants: 187,
    underReview: 45,
    shortlisted: 12,
    interviewed: 8,
};

// Recommended Jobs for Candidate
export const mockRecommendedJobs = [
    {
        id: 'job_1',
        title: 'Senior Full Stack Developer',
        company: 'TechCorp Solutions',
        location: 'San Francisco, CA',
        salary: '$120k - $180k',
        type: 'Full-time',
        skills: ['React', 'Node.js', 'TypeScript'],
        posted: '2 days ago',
        applicants: 45,
        logo: 'TC',
        match: 95,
        urgent: false,
        locationType: 'Hybrid',
    },
    {
        id: 'job_6',
        title: 'React Developer',
        company: 'WebFlow Studios',
        location: 'Remote',
        salary: '$100k - $140k',
        type: 'Full-time',
        skills: ['React', 'JavaScript', 'CSS'],
        posted: '1 day ago',
        applicants: 38,
        logo: 'WS',
        match: 92,
        urgent: true,
        locationType: 'Remote',
    },
];

// Recent Applicants for Employer
export const mockRecentApplicants = [
    {
        id: 'applicant_1',
        name: 'John Doe',
        position: 'Senior Full Stack Developer',
        appliedDate: '1 day ago',
        status: 'New',
        matchScore: 92,
        experience: '6 years',
        location: 'San Francisco, CA',
        skills: ['React', 'Node.js', 'AWS'],
        logo: 'JD',
    },
    {
        id: 'applicant_2',
        name: 'Jane Smith',
        position: 'Frontend Developer',
        appliedDate: '2 days ago',
        status: 'Reviewing',
        matchScore: 88,
        experience: '4 years',
        location: 'Remote',
        skills: ['React', 'TypeScript', 'CSS'],
        logo: 'JS',
    },
    {
        id: 'applicant_3',
        name: 'Mike Johnson',
        position: 'Backend Engineer',
        appliedDate: '3 days ago',
        status: 'Shortlisted',
        matchScore: 85,
        experience: '5 years',
        location: 'New York, NY',
        skills: ['Python', 'PostgreSQL', 'Docker'],
        logo: 'MJ',
    },
];

// Active Jobs for Employer
export const mockEmployerJobs = [
    {
        id: 'job_1',
        title: 'Senior Full Stack Developer',
        department: 'Engineering',
        location: 'San Francisco, CA',
        type: 'Full-time',
        status: 'Active',
        posted: '2024-01-15',
        applicants: 45,
        newApplicants: 5,
        views: 320,
        shortlisted: 8,
        interviewed: 3,
    },
    {
        id: 'job_2',
        title: 'Frontend Developer',
        department: 'Product',
        location: 'Remote',
        type: 'Full-time',
        status: 'Active',
        posted: '2024-01-10',
        applicants: 32,
        newApplicants: 2,
        views: 245,
        shortlisted: 5,
        interviewed: 2,
    },
];

export default {
    mockUsers,
    mockJobs,
    mockApplications,
    mockBGVDocuments,
    mockCandidateStats,
    mockEmployerStats,
    mockRecommendedJobs,
    mockRecentApplicants,
    mockEmployerJobs,
};
